apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: front-end
  type: LoadBalancer
  loadBalancerIP: 34.142.197.55