steps:
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=_deploy/gke/k8s-manifest-dev/'
      - '--image=$_PKG_HOSTNAME/$PROJECT_ID/$_GCR_HOSTNAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--recursive'
      - '--app=$_SERVICE_NAME'
      - '--namespace=$_SERVICE_NAME'
      - '--location=$_DEPLOY_REGION'
      - '--cluster=$_GKE_CLUSTER'
      - '--timeout=1m0s'
    id: Deploy

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -si http://dev.demo.leanhtuan.org | grep HTTP | cut -d' ' -f2 | if grep -Fxq 200; then echo 'front-end successfully deployed' && exit 0; else exit 1; fi
    id: verify deployment

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer $(gcloud config config-helper --format='value(credential.access_token)')" https://cloudbuild.googleapis.com/v1/projects/anthos-multi-clusters/locations/asia-southeast1/triggers/3-deploy-to-prod:run
    id: trigger prod deployment

substitutions:
  _SERVICE_NAME: front-end
  _DEPLOY_REGION: asia-southeast1-b
  _GKE_CLUSTER: gke-dev-myblog-demo
  _GCR_HOSTNAME: asia.gcr.io
  _PKG_HOSTNAME: asia-docker.pkg.dev