steps:
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=_deploy/gke/k8s-manifest/'
      - '--image=$_PKG_HOSTNAME/$PROJECT_ID/$_GCR_HOSTNAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--recursive'
      - '--expose=80'
      - '--app=$_SERVICE_NAME'
      - '--namespace=$_SERVICE_NAME'
      - '--location=$_DEPLOY_REGION'
      - '--cluster=$_GKE_CLUSTER'
    id: Deploy 
substitutions:
  _SERVICE_NAME: front-end
  _DEPLOY_REGION: asia-southeast1-b
  _GKE_CLUSTER: gke-prod-myblog-demo
  _GCR_HOSTNAME: asia.gcr.io
  _PKG_HOSTNAME: asia-docker.pkg.dev